---
# tasks file for pip
- name: install easy_install
  apt:
    name: "{{ item }}"
    install_recommends: yes
    update_cache: yes
    cache_valid_time: 3600
    autoclean: yes
    autoremove: yes
  with_items:
    - build-essential
    - python-setuptools
    - python-dev
  become: yes
  when: ansible_pkg_mgr == 'apt'

- name: install pip
  easy_install:
    name: pip
  become: yes
